sudo: false
language: node_js
node_js:
  - '8'
cache:
  directories:
    - ~/.npm
    - node_modules
dist: trusty
addons:
  apt:
    packages:
    - build-essential
    - fakeroot
    - git
    - libsecret-1-dev
notifications:
  email:
    on_success: never
    on_failure: change
branches:
  only:
    - master
    - /^greenkeeper.*$/
env:
  global:
    - APM_TEST_PACKAGES=""
    - ATOM_LINT_WITH_BUNDLED_NODE="true"
  matrix:
    - ATOM_CHANNEL=stable
    - ATOM_CHANNEL=beta
os:
  - linux
  - osx
before_install:
  # package-lock.json was introduced in npm@5
  - '[[ $(node -v) =~ ^v9.*$ ]] || npm install -g npm@latest' # skipped when using node 9
  - npm install -g greenkeeper-lockfile
install:
  - travis_retry npm install
before_script: greenkeeper-lockfile-update
script:
  - commitlint-travis
  - npm run lint
  - curl -s -O https://raw.githubusercontent.com/atom/ci/master/build-package.sh
  - chmod u+x build-package.sh
  - ./build-package.sh
  - 'echo "Skipping build/tests."'
after_script: greenkeeper-lockfile-upload
after_success:
  - npm run semantic-release
