language: node_js
node_js:
  - '8'
cache:
  directories:
    - ~/.npm
    - node_modules
dist: trusty
addons:
  apt:
    packages:
    - build-essential
    - fakeroot
    - git
    - libsecret-1-dev
notifications:
  email:
    on_success: never
    on_failure: change
branches:
  only:
    - master
    - /^release.*$/
env:
  global:
    - APM_TEST_PACKAGES=""
    - ATOM_LINT_WITH_BUNDLED_NODE="true"
  matrix:
    - ATOM_CHANNEL=stable
    - ATOM_CHANNEL=beta
os:
  - linux
  - osx
before_install:
  # package-lock.json was introduced in npm@5
  - '[[ $(node -v) =~ ^v9.*$ ]] || npm install -g npm@latest' # skipped when using node 9
  - npm install -g github-label-sync
install:
  - travis_retry npm install
  # See https://github.com/atom/ci
  - curl -s -O https://raw.githubusercontent.com/atom/ci/master/build-package.sh
  - chmod u+x build-package.sh
  - ./build-package.sh
  # Add apm to the PATH
  - export PATH=$PATH:~/atom/usr/bin
script:
  - commitlint-travis
  - npm run lint
jobs:
  include:
    - stage: deploy
      if: branch = master
      script:
        - travis_retry github-label-sync -a "$GH_TOKEN" -l 'https://git.io/fAe5i' seantrane/balanced-theme-for-atom
        - npm run semantic-release
      env: ATOM_CHANNEL=stable
